#!/usr/bin/env bash
set -euo pipefail

# Must be run from the project root
PROJECT_ROOT="$(pwd)"

# Resolve HOME safely
HOME_DIR="${HOME:?HOME is not set}"

# Resolve XDG cache root (shell-expanded, not compose-expanded)
XDG_CACHE_ROOT="${XDG_CACHE_HOME:-$HOME_DIR/.cache}"

# vcpkg locations (adjust if you intentionally keep vcpkg elsewhere)
VCPKG_ROOT="${VCPKG_ROOT:-$HOME_DIR/vcpkg}"
VCPKG_CACHE_HOST="${XDG_CACHE_ROOT}/vcpkg"

# Create cache dir if missing
mkdir -p "${VCPKG_CACHE_HOST}"

# todo: decide between /dev/dri and /dev/dxg.

# Write .env atomically
cat > .devcontainer/.env <<EOF
# Generated by scripts/generate-env.sh
# Do not edit by hand unless you know what you're doing

PROJECT_ROOT=${PROJECT_ROOT}
VCPKG_ROOT=${VCPKG_ROOT}
VCPKG_CACHE_HOST=${VCPKG_CACHE_HOST}
EOF

echo "Wrote .devcontainer/.env with:"
echo "  PROJECT_ROOT=${PROJECT_ROOT}"
echo "  VCPKG_ROOT=${VCPKG_ROOT}"
echo "  VCPKG_CACHE_HOST=${VCPKG_CACHE_HOST}"
echo "Now run: 'xhost +local: && podman-compose -f .devcontainer/compose.yaml run --rm dev'"
